# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcqlsh < Formula
  desc "Cassandra command line shell written in Go"
  homepage "https://github.com/npenkov/gcqlsh"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/npenkov/gcqlsh/releases/download/v0.1.3/gcqlsh_darwin_x86_64.tar.gz"
      sha256 "f8b22e27a8a95e79744ee8188cfa9adc5c9d9d8a91037239266ed233b3ca465a"

      def install
        bin.install "gcqlsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/npenkov/gcqlsh/releases/download/v0.1.3/gcqlsh_darwin_arm64.tar.gz"
      sha256 "9da4b76a4f9a5a478c05b9ccbb9ad74c330cbff10e6de7b1c087d556b581784c"

      def install
        bin.install "gcqlsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/npenkov/gcqlsh/releases/download/v0.1.3/gcqlsh_linux_x86_64.tar.gz"
      sha256 "9bf44c779870d25086ab9e3608828fd45cb3b4eee15408f816d326156f024786"
      def install
        bin.install "gcqlsh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/npenkov/gcqlsh/releases/download/v0.1.3/gcqlsh_linux_arm64.tar.gz"
      sha256 "884c23fafcacdddde2b6c68616ca6dd0f4ddcec766ae1a59bd1b953de3699738"
      def install
        bin.install "gcqlsh"
      end
    end
  end

  test do
    system "#{bin}/gcqlsh -v"
  end
end
